# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 12:02
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0005_auto_20180705_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='arttag',
            options={'verbose_name': '分类标签', 'verbose_name_plural': '分类标签'},
        ),
        migrations.AlterField(
            model_name='art',
            name='summary',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='概述'),
        ),
    ]
