# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20180705_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=13, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
